"""create cases tables

Revision ID: 121138e1313d
Revises: bad4c0b492cf
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "121138e1313d"
down_revision: str | Sequence[str] | None = "bad4c0b492cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_counters",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_case_counters_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("organization_id", "year", name=op.f("pk_case_counters")),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "closed",
                "archived",
                "under_legal_hold",
                "pending_deletion",
                "deleted",
                name="casestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'closed', 'archived', 'under_legal_hold', 'pending_deletion', 'deleted')",
            name=op.f("ck_cases_status_valid"),
        ),
        sa.CheckConstraint("length(btrim(title)) > 0", name=op.f("ck_cases_title_not_blank")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_cases_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cases_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
        sa.UniqueConstraint("organization_id", "id", name="uq_cases_organization_id_id"),
        sa.UniqueConstraint("organization_id", "reference", name="uq_cases_organization_reference"),
    )
    op.create_table(
        "case_members",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("lead", "editor", "viewer", name="caserole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('lead', 'editor', 'viewer')", name=op.f("ck_case_members_role_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "case_id"],
            ["cases.organization_id", "cases.id"],
            name="fk_case_members_case",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "user_id"],
            ["memberships.organization_id", "memberships.user_id"],
            name="fk_case_members_membership",
        ),
        sa.PrimaryKeyConstraint("case_id", "user_id", name=op.f("pk_case_members")),
    )
    op.create_index(op.f("ix_case_members_user_id"), "case_members", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_members_user_id"), table_name="case_members")
    op.drop_table("case_members")
    op.drop_table("cases")
    op.drop_table("case_counters")
    # ### end Alembic commands ###
