"""create evidence tables

Revision ID: 5deb38bfec00
Revises: 121138e1313d
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5deb38bfec00"
down_revision: str | Sequence[str] | None = "121138e1313d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_counters",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_counters_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("organization_id", "year", name=op.f("pk_evidence_counters")),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=20), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "preserved",
                "failed",
                name="evidencestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("preserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'preserved') = (preserved_at IS NOT NULL)",
            name=op.f("ck_evidence_preserved_at_matches_status"),
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_evidence_sha256_format")),
        sa.CheckConstraint(
            "status IN ('pending', 'preserved', 'failed')", name=op.f("ck_evidence_status_valid")
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_evidence_size_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id", "case_id"],
            ["cases.organization_id", "cases.id"],
            name="fk_evidence_case",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_evidence_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint(
            "organization_id", "reference", name="uq_evidence_organization_reference"
        ),
        sa.UniqueConstraint("storage_key", name=op.f("uq_evidence_storage_key")),
    )
    op.create_index(op.f("ix_evidence_case_id"), "evidence", ["case_id"], unique=False)
    op.create_index(
        "uq_evidence_case_sha256_not_failed",
        "evidence",
        ["case_id", "sha256"],
        unique=True,
        postgresql_where=sa.text("status <> 'failed'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_evidence_case_sha256_not_failed",
        table_name="evidence",
        postgresql_where=sa.text("status <> 'failed'"),
    )
    op.drop_index(op.f("ix_evidence_case_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("evidence_counters")
    # ### end Alembic commands ###
